### PR TITLE
Draft: Updates to modernize component

### PR DESCRIPTION
**Pull request by zackbcom**
## Changes
-  Linting using HA Core dev tooling
- Added all the types
- Updated to use Standard HA classes / enums
- Swapped to `_attr_media_title` style attributes
- Reduced duplicate code form `MediaPlayerEntity` class.
- Swapped to `.get()` when pulling data from responses so that we don't error on key not found.
- Swapped to `/api/system/status` as this endpoint is always active even with FPP Daemon is offline.
- Added `_base_url` 

Changed name to FPP, revert these if you dont wan't that change.

## TODO
- Build API client for FPP
- Swap to async
- Swap from requests to `aiohttp` -> `from homeassistant.helpers.aiohttp_client import async_get_clientsession`
- Enable UI Config
- Leverage SSPS/easyconfig to pull `_fpp` from mdns for auto config using https://developers.home-assistant.io/docs/network_discovery/

### CODE REVIEW

**Comment by Aleks130699** [comment]
Thank you for your work, I will check your corrections in the near future, and if everything works as it should, I will accept them

**Comment by zackbcom** [comment]
> Thank you for your work, I will check your corrections in the near future, and if everything works as it should, I will accept them

Feel free to make changes to merge request before accepting. 

I've been looking at the fpp and xlights code for how they automatically search for the fpp clients. Seems like some mdns, bonjour, and custom multicast packets. 

Would be awesome to work our way to ui setup, even if it's just setting ips and names.

**Comment by Aleks130699** [comment]
> > Thank you for your work, I will check your corrections in the near future, and if everything works as it should, I will accept them
> 
> Feel free to make changes to merge request before accepting.
> 
> I've been looking at the fpp and xlights code for how they automatically search for the fpp clients. Seems like some mdns, bonjour, and custom multicast packets.
> 
> Would be awesome to work our way to ui setup, even if it's just setting ips and names.

I had an idea to do an automatic search for instances, but I still couldn't figure out how to do it correctly, about configuring it from the interface, I'll try to do it, but I haven't done it yet, and this is generally my work on integrations

**Comment by Aleks130699** [comment]
@zackbcom I worked hard on the integration, and added a setting from the interface to it, and also started working on automatic search, but so far this is not clear to me, I'll deal with switching the system to asynchronous mode a little later, since I already figured out how to do this when I made these settings, if you don't have more experience could take a look, maybe there's something I did wrong https://github.com/Aleks130699/ha-fpp/discussions/12

**Pull request merged**
